apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y23d5ffzr-go 
  janus-idp.io/tekton: y23d5ffzr-go
  backstage.io/kubernetes-id: y23d5ffzr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y23d5ffzr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  